import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import styles from '@/styles/Home.module.css'
import { useAuth } from '@/auth/auth'
import { useEffect } from 'react';
import { messaging, firebase as firebaseClient  } from "../firebase-utils/firebase-client";
import { getToken, onMessage } from 'firebase/messaging'

export default function Home() {
  const { user } = useAuth();
  const requestPermission =async () => {
    const permission = await Notification.requestPermission();
    if(permission ==='granted') {
      console.log('Granted');
      const token = await getToken(messaging, { vapidKey: process.env.NEXT_WEBPUSH_CERTFICATE})
      console.log(token)
    } else if(permission === 'denied') {
      console.log('Denied')
    }
  }

  useEffect(() => {
    requestPermission();
    messaging.(function(payload  ) {
      console.log('Received background message ', payload);
    
      const notificationTitle = payload?.notification?.title;
      const notificationOptions = {
        body: payload?.notification?.body,
      };
    
      console.log(notificationTitle, notificationOptions)
      // self.registration.showNotification(notificationTitle,
      //   notificationOptions);
    });
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ padding: '40px' }}>
        <p>{`User ID: ${user ? user.uid : 'no user signed in'}`}</p>

        <p>
          <Link href="/authenticated">Go to authenticated route
          </Link>
        </p>
        <p>
          <Link href="/login">
            Login
          </Link>
        </p>
      </div>
      </main>
    </>
  )
}
