import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import styles from '@/styles/Home.module.css'
import { useAuth } from '@/auth/auth'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user } = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ padding: '40px' }}>
        <p>{`User ID: ${user ? user.uid : 'no user signed in'}`}</p>

        <p>
          <Link href="/authenticated">Go to authenticated route
          </Link>
        </p>
        <p>
          <Link href="/login">
            Login
          </Link>
        </p>
      </div>
      </main>
    </>
  )
}
